---
n_estimators:
  # - 5
  # - 9
  - 100
  - 50
  - 150
  - 200
max_depth:
  - 3
  # - 5
  - 7
  # - 9
  - 10
  - 50
  - 100
  - 150
population_size:
  # - 5
  # - 10
  # - 15
  - 20
  - 50
generations:
  # - 1
  # - 3
  # - 5
  - 10
  - 20
