---
#### BASELINE GRIDSEARCH
# transfer_model:
#     - switch
# attention_hidden_size:
#     - 8
#     - 16
#     - 32
#     - 64
# rnn_ncells:
#     - 8
#     - 16
#     - 32
#     - 64
# primary_epochs:
#     - 30
#     - 500
